#!/bin/bash

mkdir holdme
mkdir holdme/errata
if ! [ -x /home/dev/.local/bin/ruff ]; then pip install ruff; fi
mv errata/migrations/000[23456789]*py holdme/errata/
rm errata/migrations/0001_initial.py
./manage.py makemigrations errata
sed -i 's/# Generated by .*$/# Copyright The IETF Trust 2025-2026, All Rights Reserved/' errata/migrations/0001_initial.py
mv holdme/errata/* errata/migrations/
ruff format errata
rm -r holdme
ruff check --fix .
echo "Inspect, and if necessary rename data migrations and update their dependencies"
