# Generated by Django 5.2.9 on 2025-12-18 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('errata_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.JSONField(blank=True, default=[]),
            preserve_default=False,
        ),
    ]
