name: Run Tests

on:
  pull_request: {}
  push:
    paths-ignore:
      - '.devcontainer/**'
      - '.github/**'
      - '.vscode/**'
      - 'k8s/**'
      - 'README.md'
  workflow_dispatch: {}

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v6

    - name: Setup Python
      uses: actions/setup-python@v6.2.0
      with:
        python-version: '3.12'

    - name: Install pip packages
      run: |
        pip3 --disable-pip-version-check --no-cache-dir install --no-warn-script-location -r requirements.txt
    
    - name: Run all tests
      run: |
        ./manage.py test
