name: Run Tests

on:
  pull_request: {}
  push:
    paths-ignore:
      - '.devcontainer/**'
      - '.github/**'
      - '.vscode/**'
      - 'k8s/**'
      - 'README.md'
  workflow_dispatch: {}

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v6

    - name: Setup Python
      uses: actions/setup-python@v6.2.0
      with:
        python-version: '3.12'

    - name: Setup Node.js environment
      uses: actions/setup-node@v6.4.0
      with:
        node-version: '24.x'

    - name: Install dependencies
      run: |
        npx --yes @openapitools/openapi-generator-cli generate --generator-key datatracker
        pip3 --disable-pip-version-check --no-cache-dir install --no-warn-script-location -r requirements.txt
    
    - name: Run all tests
      env:
        DJANGO_SETTINGS_MODULE: 'errata_project.settings.test'
        ERRATA_OIDC_RP_CLIENT_ID: '079065'
        ERRATA_OIDC_RP_CLIENT_SECRET: '788eb5a13ee8e233e91a42c88b5ad1736342c5b98e3bcec834d01074'
      run: |
        ./manage.py test
